[tool.poetry]
name = "sl-transformer"
version = "0.1.0"
description = ""
authors = ["Cleison Amorim <cca5@cin.ufpe.br>"]

[tool.poetry.dependencies]
python = "^3.7"
commons-python = { git = "https://github.com/amorim-cleison/commons-python.git", branch = "develop" }
torch = { git = "https://github.com/pytorch/pytorch.git", tag = "v1.6.0" }
torchvision = { git = "https://github.com/pytorch/vision.git", tag = "v0.7.0" }
torchtext= "^0.6.0"
spacy = "^2.3.2"
seaborn = "^0.11.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
yapf = "^0.30.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
