[tool.poetry]
name = "sl-transformer"
version = "0.1.0"
description = ""
authors = ["Cleison Amorim <cca5@cin.ufpe.br>"]

[tool.poetry.dependencies]
python = "^3.7"
# torchvision = [
#     # { platform = "win32", url = "http://download.pytorch.org/whl/cpu/torchvision-0.7.0%2Bcpu-cp37-cp37m-win_amd64.whl" },
#     { platform = "win32", version = "~0.7.0+cpu" },
#     { platform = "linux", version = "~0.7.0" }
# ]
torchtext= "^0.6.0"
spacy = "^2.3.2"
seaborn = "^0.11.0"
torchvision = "~0.7.0"
# torchvision = [
#     { url = "http://download.pytorch.org/whl/cpu/torchvision-0.7.0%2Bcpu-cp37-cp37m-win_amd64.whl", platform = "win32" },
#     { version = "~0.7.0", platform = "linux" }
# ]


[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
