debug: False
log: Null

dataset:
  dataset_dir: ../../work/dataset/asl-phono/phonology/3d
  fields: [
    orientation_dh,
    orientation_ndh, 
    movement_dh, 
    movement_ndh,
    handshape_dh, 
    handshape_ndh, 
    # mouth_openness
  ]
  samples_min_freq: 2   # How many samples for the label should exist in dataset for the label to be considered?
  train_split_ratio: 0.7
  val_split_ratio: 0.1
  composition_strategy: as_words

model:
  model_type: Transformer
  N: 6
  d_model: 512
  d_ff: 2048
  h: 8
  dropout: 0.1

training:
  seed: 1
  epochs: 10 # Original: 100
  batch_size: 50
  warm_up: 400 # Original: 4000
  lr: 0.5
  lr_step_gamma: 0.95
  lr_step_size: 1.0
  log_interval: 5
  checkpoint_dir: ../../work/sl-transformer/checkpoint
  checkpoint_interval: 1
  checkpoint_last_only: True
