debug: False
log: Null

dataset_args:
  dataset_dir: ../../work/dataset/asl-phono/phonology/3d
  fields: [
    orientation_dh,
    orientation_ndh, 
    movement_dh, 
    movement_ndh,
    handshape_dh, 
    handshape_ndh, 
    # mouth_openness
  ]
  samples_min_freq: 2   # How many samples for the label should exist in dataset for the label to be considered?
  train_split_ratio: 0.7
  val_split_ratio: 0.1
  composition_strategy: as_words

# model_args:
#   model_type: transformer
#   input_size: 512
#   hidden_size: 2048
#   num_layers: 6
#   dropout: 0.1
#   # Transformer:
#   num_heads: 8

model_args:
  model_type: lstm
  input_size: 512
  hidden_size: 2048
  num_layers: 2
  dropout: 0.3


training_args:
  seed: 1
  epochs: 100 # Original: 100
  batch_size: 50
  # warm_up: 400 # Original: 4000
  lr: 0.50
  lr_step_gamma: 0.95
  lr_step_size: 1
  log_interval: 5
  checkpoint_dir: ../../work/sl-transformer/checkpoint
