seed: 1
debug: False
log: Null
model_type: Transformer

# transfer_learning:
#   enabled: False
#   model_path: ../../work/sl-transformer/transfer-model/iwslt.pt
#   model_url: https://s3.amazonaws.com/opennmt-models/iwslt.pt

dataset:
  dataset_dir: ../../work/dataset/asl-phono/phonology/3d
  path: ../../work/dataset/data-debug.json
  fields: [
    orientation_dh,
    orientation_ndh, 
    movement_dh, 
    movement_ndh,
    handshape_dh, 
    handshape_ndh, 
    # mouth_openness
  ]
  samples_min_freq: 2
  vocab_min_freq: 2
  max_len_sentence: 100
  train_split_ratio: 0.7
  val_split_ratio: 0.1
  composition_strategy: as_words

model:
  N: 6
  d_model: 512
  d_ff: 2048
  h: 8
  dropout: 0.1

training:
  epochs: 10 # Original: 100
  batch_size: 50
  warm_up: 400 # Original: 4000
  lr: 0.5
  lr_step_gamma: 0.95
  lr_step_size: 1.0
  log_interval: 5
  checkpoint_dir: ../../work/sl-transformer/checkpoint
  checkpoint_interval: 1
  checkpoint_last_only: True
