debug: False
devices: [ ]
log: Null

transfer_learning:
  enabled: False
  model_path: ../../work/sl-transformer/transfer-model/iwslt.pt
  model_url: https://s3.amazonaws.com/opennmt-models/iwslt.pt

dataset:
  attributes_dir: ../../work/dataset/phono/3d
  path: ../../work/dataset/data-debug.json
  fields: [
    orientation_dh,
    orientation_ndh, 
    handshape_dh, 
    handshape_ndh, 
    movement_dh_st, 
    movement_ndh_st,
    # mouth_openness
  ]
  samples_min_freq: 2
  vocab_min_freq: 2
  max_len_sentence: 100
  train_split_ratio: 0.7
  composition_strategy: as_words

model:
  N: 6
  d_model: 512
  d_ff: 2048
  h: 8
  dropout: 0.1

training:
  epochs: 100
  batch_size: 50
  warm_up: 400 # Original: 4000
  lr: 0
  betas: [0.9, 0.98]
  eps: 0.000000001
  label_smoothing: 0.1
  log_steps_interval: 5
  checkpoint_dir: ../../work/sl-transformer/checkpoint
  checkpoint_interval: 1
  checkpoint_last_only: True
